function stylesheet(A)
%---Program window---%
fig=figure('Name','Td signal process',...
'Units','normalized',...
'Position',[0.05 0.05 0.9 0.85],...
'NumberTitle','off');

%---Title---%

uicontrol('Style','text',...
            'Units','normalized',...
            'backgroundcolor',[0.5,0.75,0.75],...
            'Position',[0.019 0.95 0.30 0.03],...
            'String', 'Signal simulator',...
            'Fontsize',10);       

%---Parameters Input signal---%
SignalParameters=uipanel('Visible','on',...
                     'BackgroundColor',[0.75,0.75,0.75],...
                     'ForegroundColor','black',...
                     'Title','Parameters',...
                     'FontSize',9,...
                     'TitlePosition','centertop',...
                     'Position',[0.17 0.65 0.15 0.28]);
            
BA=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.54 0.64 0.4 0.15],...
            'String',A,...
            'Tag','amplitudine',...
            'Callback','chart',...
            'Parent',SignalParameters);

BAtext=uicontrol('Style','text',...
                'Units','normalized',...
                'Position',[0.07 0.64 0.4 0.15],...
                'BackgroundColor',[0.75,0.75,0.75],...
                'ForegroundColor','black',...
                'String', 'A[V]',...
                'Fontsize', 9,...
                'FontWeight','demi',...
                'HorizontalAlignment','left',...
                'Parent',SignalParameters);

%---Exit---%
Exit=uicontrol('Style','pushbutton',...
                  'Units','normalized',...
                  'Position',[0.035 0.70 0.08 0.08],...
                  'backgroundcolor','red',...
                  'Fontsize',12,...
                  'String','Exit',...
                  'Tag','iesire',...
                  'TooltipString','Apasati butonul pentru a iesi din program.',...
                  'Callback','close');
%---RESET---%

uicontrol('Style','pushbutton',... % create a reset button
'Units','normalized',...
'Position',[0.035 0.78 0.08 0.08],...
'string','RESET',...
'TooltipString','Apasati butonul pentru a reseta programul.',...
'Callback','close;main');
              
end
